/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fruit;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mirmo
 */
public class Fruit extends javax.swing.JFrame {

    /**
     * Creates new form Fruit
     */
    public Fruit() {
        initComponents();
        Fruit ();
    }
     DefaultTableModel  model = new DefaultTableModel();
    public void Fruit (){
        
        model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]{
            "Apple"
        });
        model.addRow(new Object[]{
            "Mango"
        });
        model.addRow(new Object[]{
            "Banana"
        });
         model.addRow(new Object[]{
            "Blueberries"
        });
          model.addRow(new Object[]{
            "Cherries"
        });
         model.addRow(new Object[]{
            "Grapes"
        });
          model.addRow(new Object[]{
            "Jackfruit"
        });
           model.addRow(new Object[]{
            "Lychee"
        });
            model.addRow(new Object[]{
            "Orange"
        });
             model.addRow(new Object[]{
            "Papaya"
        });
         model.addRow(new Object[]{
            "Dragonfruit"
        });
          model.addRow(new Object[]{
            "Pineapple"
        });
           model.addRow(new Object[]{
            "Strawberries"
        });
         model.addRow(new Object[]{
            "Watermelon"
        });
        
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtsub = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fruit Shop");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(403, 403, 403)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Subtotal");

        txtsub.setBackground(new java.awt.Color(0, 0, 0));
        txtsub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsub.setForeground(new java.awt.Color(0, 153, 0));
        txtsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtsub, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtsub, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addGap(35, 35, 35))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fruit"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Qty", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int sum = 0;
        int fruits = jTable1.getSelectedRow();
        int price;
        int qty;
        
        if(fruits == 0)
        {
            price = 80;
            qty   = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model = (DefaultTableModel)jTable2.getModel();
            int tot = price*qty;
            
            model.addRow(new Object[]{
                "Apple",
                price ,
                qty,
                tot,
            });
        }
        if(fruits == 1)
        {
            price = 75;
            qty   = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model = (DefaultTableModel)jTable2.getModel();
            int tot = price*qty;
            
            model.addRow(new Object[]{
                "Mango",
                price ,
                qty,
                tot,
            });
        }
        if(fruits == 2)
        {
            price = 45;
            qty   = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model = (DefaultTableModel)jTable2.getModel();
            int tot = price*qty;
            
            model.addRow(new Object[]{
                "Banana",
                price ,
                qty,
                tot,
            });
        }
         if(fruits == 3)
        {
            price = 90;
            qty   = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model = (DefaultTableModel)jTable2.getModel();
            int tot = price*qty;
            
            model.addRow(new Object[]{
                "Blueberries",
                price ,
                qty,
                tot,
            });
        }
         if(fruits == 4)
        {
            price = 85;
            qty   = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model = (DefaultTableModel)jTable2.getModel();
            int tot = price*qty;
            
            model.addRow(new Object[]{
                "Cherries",
                price ,
                qty,
                tot,
            });
        }
         if(fruits == 5)
        {
            price = 100;
            qty   = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model = (DefaultTableModel)jTable2.getModel();
            int tot = price*qty;
            
            model.addRow(new Object[]{
                "Grapes",
                price ,
                qty,
                tot,
            });
        }
         if(fruits == 6)
        {
            price = 150;
            qty   = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model = (DefaultTableModel)jTable2.getModel();
            int tot = price*qty;
            
            model.addRow(new Object[]{
                "Jackfruit",
                price ,
                qty,
                tot,
            });
        }
         if(fruits == 7)
        {
            price = 100;
            qty   = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model = (DefaultTableModel)jTable2.getModel();
            int tot = price*qty;
            
            model.addRow(new Object[]{
                "Lychee",
                price ,
                qty,
                tot,
            });
        }
          if(fruits == 8)
        {
            price = 110;
            qty   = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model = (DefaultTableModel)jTable2.getModel();
            int tot = price*qty;
            
            model.addRow(new Object[]{
                "Orange",
                price ,
                qty,
                tot,
            });
        }
          if(fruits == 9)
        {
            price = 70;
            qty   = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model = (DefaultTableModel)jTable2.getModel();
            int tot = price*qty;
            
            model.addRow(new Object[]{
                "Papaya",
                price ,
                qty,
                tot,
            });
        }
          if(fruits == 10)
        {
            price = 400;
            qty   = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model = (DefaultTableModel)jTable2.getModel();
            int tot = price*qty;
            
            model.addRow(new Object[]{
                "Dragonfruit",
                price ,
                qty,
                tot,
            });
        }
          if(fruits == 11)
        {
            price = 40;
            qty   = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model = (DefaultTableModel)jTable2.getModel();
            int tot = price*qty;
            
            model.addRow(new Object[]{
                "Pineapple",
                price ,
                qty,
                tot,
            });
        }
          if(fruits == 12)
        {
            price = 180;
            qty   = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model = (DefaultTableModel)jTable2.getModel();
            int tot = price*qty;
            
            model.addRow(new Object[]{
                "Strawberries",
                price ,
                qty,
                tot,
            });
        }
          if(fruits == 13)
        {
            price = 140;
            qty   = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model = (DefaultTableModel)jTable2.getModel();
            int tot = price*qty;
            
            model.addRow(new Object[]{
                "Watermelon",
                price ,
                qty,
                tot,
            });
        }
         
         
        for(int i=0; i<jTable2.getRowCount(); i++)
        {
            sum = sum + Integer.parseInt(jTable2.getValueAt(i, 3).toString());
        }
        txtsub.setText(String.valueOf(sum));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                setVisible(false);
                Fruit object = new Fruit();
                object.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fruit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtsub;
    // End of variables declaration//GEN-END:variables

    
}
